import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { CheckCircle2, ShieldAlert, XCircle } from "lucide-react";
import { useState } from "react";
import { api } from "../api";
import { ErrorState, Loading, PageHeading, Severity, time } from "../components/Ui";

export function DecisionDeskPage() {
  const client = useQueryClient(); const scenarios = useQuery({ queryKey: ["responses"], queryFn: api.responses }); const [comments, setComments] = useState<Record<string, string>>({});
  const decide = useMutation({ mutationFn: ({ scenarioId, optionId, decision, comment }: { scenarioId: string; optionId: string; decision: "approve" | "reject"; comment: string }) => api.decideResponse(scenarioId, { optionId, decision, comment }), onSuccess: () => client.invalidateQueries({ queryKey: ["responses"] }) });
  if (scenarios.isLoading) return <Loading label="Reading governed response scenarios" />; if (scenarios.error) return <ErrorState error={scenarios.error} />;
  const open = scenarios.data!.filter((scenario) => ["awaiting_decision", "awaiting_approval"].includes(scenario.status));
  return <><PageHeading eyebrow="Phase 20 / governed decisions" title="Response decision desk" copy="Approve or reject a policy-eligible recommendation with a recorded rationale. Approval never authorizes execution in Cascadia." />
    <section className="decision-boundary"><ShieldAlert size={17} /><span>Every decision is attributable, policy-checked, and append-only. <b>Execution remains disabled.</b></span></section>
    <div className="decision-stack">{open.map((scenario) => <section className="data-panel" key={scenario.id}><header><div><span className="panel-label">Scenario {scenario.id.slice(0, 8)} / {time(scenario.generatedAt)}</span><h2>{scenario.status.replaceAll("_", " ")}</h2></div><span className={`disposition disposition--${scenario.status}`}>{scenario.decisions.length} recorded decisions</span></header><div className="decision-options">{scenario.options.map((option) => <article key={option.id}><div className="option-top"><div><b>{option.title}</b><small>{option.actionType.replaceAll("_", " ")} · {option.approvalMode.replaceAll("_", " ")}</small></div><Severity value={option.eligible ? "low" : "high"} /></div><p>{option.policyChecks.map((check) => check.reason).join(" ")}</p><div className="option-metrics"><span>Benefit <b>{option.securityBenefit}</b></span><span>Impact <b>{option.operationalImpact}</b></span><span>Residual <b>{option.residualRiskScore}</b></span><span>Approvals <b>{option.requiredApprovals}</b></span></div>{option.eligible ? <div className="decision-form"><textarea value={comments[option.id] ?? ""} onChange={(event) => setComments((current) => ({ ...current, [option.id]: event.target.value }))} placeholder="Required decision rationale" rows={2} /><div><button disabled={!comments[option.id]?.trim() || decide.isPending} onClick={() => decide.mutate({ scenarioId: scenario.id, optionId: option.id, decision: "reject", comment: comments[option.id]! })}><XCircle size={14} /> Reject</button><button className="button button--primary" disabled={!comments[option.id]?.trim() || decide.isPending} onClick={() => decide.mutate({ scenarioId: scenario.id, optionId: option.id, decision: "approve", comment: comments[option.id]! })}><CheckCircle2 size={14} /> Record approval</button></div></div> : <p className="blocked-copy">Blocked by policy; this option cannot be approved.</p>}</article>)}</div></section>)}{!open.length && <section className="data-panel empty"><span>00</span><h3>No pending response decisions</h3><p>New scenarios appear after an authorized operator runs a policy-governed response simulation.</p></section>}</div>
  </>;
}
